// <auto-generated />
using System;
using APICadastro.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APICadastro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231229103941_AddTiposAcesso")]
    partial class AddTiposAcesso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APICadastro.Models.Inativacao", b =>
                {
                    b.Property<int>("InativacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InativacaoID"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("InativacaoID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inativacoes");
                });

            modelBuilder.Entity("APICadastro.Models.TipoAcesso", b =>
                {
                    b.Property<int>("TipoAcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoAcessoId"));

                    b.Property<string>("Tipos")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TipoAcessoId");

                    b.ToTable("TiposAcesso");
                });

            modelBuilder.Entity("APICadastro.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAcessoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("TipoAcessoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("APICadastro.Models.Inativacao", b =>
                {
                    b.HasOne("APICadastro.Models.Usuario", "Usuario")
                        .WithMany("Inativacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APICadastro.Models.Usuario", b =>
                {
                    b.HasOne("APICadastro.Models.TipoAcesso", "TipoAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAcesso");
                });

            modelBuilder.Entity("APICadastro.Models.TipoAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("APICadastro.Models.Usuario", b =>
                {
                    b.Navigation("Inativacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
